/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminRecord {
  'principal' : Principal,
  'createdAt' : bigint,
  'role' : UserRole,
  'updatedAt' : bigint,
}
export interface BannerImage {
  'id' : bigint,
  'bannerType' : BannerImageType,
  'size' : bigint,
  'mimeType' : string,
  'filename' : string,
  'storageUrl' : string,
  'uploadedAt' : bigint,
  'uploadedBy' : Principal,
}
export type BannerImageType = { 'mainBanner' : null } |
  { 'ctaBanner' : null };
export interface BlogComment {
  'id' : bigint,
  'content' : string,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'approved' : boolean,
  'parentId' : [] | [bigint],
  'postId' : bigint,
}
export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'likeCount' : bigint,
  'content' : string,
  'coverImageId' : string,
  'published' : boolean,
  'createdAt' : bigint,
  'slug' : string,
  'tags' : Array<string>,
  'publishedAt' : bigint,
  'author' : string,
  'updatedAt' : bigint,
  'authorAvatarId' : string,
  'excerpt' : string,
  'commentCount' : bigint,
  'category' : string,
  'authorTitle' : string,
  'readTimeMinutes' : bigint,
}
export interface CommercialSpecItem { 'key' : string, 'value' : string }
export interface CommercialVehicle {
  'id' : string,
  'specifications' : Array<CommercialSpecItem>,
  'subCategory' : string,
  'brochureUrl' : string,
  'isPublished' : boolean,
  'displayOrder' : bigint,
  'footnote' : string,
  'name' : string,
  'createdAt' : bigint,
  'slug' : string,
  'mainImages' : Array<string>,
  'description' : string,
  'chassisImage' : string,
  'heroImage' : string,
  'chassisPrice' : bigint,
  'updatedAt' : bigint,
  'cabinImage' : string,
  'category' : string,
  'heroTitle' : string,
  'heroSubtext' : string,
}
export interface CreditRequirementItem { 'item' : string }
export interface CreditRequirementTab {
  'id' : string,
  'order' : bigint,
  'tabName' : string,
  'requirements' : Array<CreditRequirementItem>,
}
export interface CreditSettings {
  'provisionPercent' : number,
  'insurancePercent' : number,
  'adminFee' : bigint,
  'footnote' : string,
  'updatedAt' : bigint,
  'interestRatePerYear' : number,
}
export interface Lead {
  'dp' : bigint,
  'id' : string,
  'otr' : bigint,
  'tenor' : bigint,
  'vehicleType' : string,
  'source' : string,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'address' : string,
  'monthlyInstallment' : bigint,
  'phone' : string,
}
export interface MediaAsset {
  'id' : bigint,
  'size' : bigint,
  'mimeType' : string,
  'filename' : string,
  'storageUrl' : string,
  'uploadedAt' : bigint,
  'uploadedBy' : Principal,
}
export interface PassengerVehicle {
  'id' : bigint,
  'heroImageUrl' : string,
  'vehicleName' : string,
  'vehicleType' : string,
  'brochureUrl' : string,
  'displayOrder' : bigint,
  'createdAt' : bigint,
  'slug' : string,
  'publishStatus' : boolean,
  'description' : string,
  'variants' : Array<VehicleVariant>,
  'ctaButtonLabel' : string,
  'specTabs' : Array<SpecTab>,
  'updatedAt' : bigint,
  'ctaText' : string,
  'ctaSubtext' : string,
  'ctaButtonUrl' : string,
  'titleImageUrl' : [] | [string],
  'footnotes' : Array<string>,
  'heroBannerVideoId' : [] | [string],
  'aftersaleImages' : Array<string>,
}
export interface Promotion {
  'id' : bigint,
  'title' : string,
  'active' : boolean,
  'endDate' : bigint,
  'vehicleRef' : [] | [string],
  'createdAt' : bigint,
  'slug' : string,
  'tags' : Array<string>,
  'description' : string,
  'vehicleRefType' : [] | [string],
  'updatedAt' : bigint,
  'termsAndConditions' : string,
  'imageId' : [] | [string],
  'startDate' : bigint,
}
export interface SpecCell { 'value' : string, 'colSpan' : bigint }
export interface SpecRow { 'cells' : Array<SpecCell> }
export interface SpecTab {
  'title' : string,
  'rows' : Array<SpecRow>,
  'columns' : Array<string>,
}
export interface Testimonial {
  'id' : bigint,
  'customerName' : string,
  'vehicleName' : string,
  'active' : boolean,
  'vehicleRef' : string,
  'vehicleUrl' : string,
  'createdAt' : bigint,
  'vehicleRefType' : string,
  'updatedAt' : bigint,
  'message' : string,
  'rating' : bigint,
  'customerPhotoId' : string,
  'customerCity' : string,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'super_admin' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VehicleColor {
  'colorName' : string,
  'vehicleImage' : string,
  'price' : bigint,
  'colorImage' : string,
}
export interface VehicleVariant {
  'thumbnailUrl' : string,
  'hasPremiumOption' : boolean,
  'variantName' : string,
  'colors' : Array<VehicleColor>,
  'price' : bigint,
}
export interface Visit {
  'id' : string,
  'referrer' : string,
  'visitedAt' : bigint,
  'pageUrl' : string,
  'deviceType' : string,
  'browser' : string,
  'sessionId' : string,
  'userAgent' : string,
  'ipAddress' : string,
}
export interface VisitorSession {
  'lastActivity' : bigint,
  'isOnline' : boolean,
  'firstVisit' : bigint,
  'sessionId' : string,
  'ipAddress' : string,
}
export interface VisitorStats {
  'visitorsThisWeek' : bigint,
  'visitorsYesterday' : bigint,
  'visitorsThisYear' : bigint,
  'onlineNow' : bigint,
  'totalVisitors' : bigint,
  'visitorsToday' : bigint,
  'pageViewsToday' : bigint,
  'visitorsThisMonth' : bigint,
}
export interface WebsiteSettings {
  'mainBannerImageId' : [] | [bigint],
  'dealerAddress' : string,
  'salesConsultantPhotoId' : [] | [bigint],
  'operationalHours' : string,
  'lastUpdated' : bigint,
  'mainBannerVideoId' : [] | [bigint],
  'instagramUrl' : string,
  'ctaBannerImageId' : [] | [bigint],
  'siteName' : string,
  'footerAboutText' : [] | [string],
  'mainBannerImageId2' : [] | [bigint],
  'contactEmail' : string,
  'contactWhatsapp' : string,
  'youtubeUrl' : string,
  'facebookUrl' : string,
  'salesConsultantName' : [] | [string],
  'homepageBannerMode' : [] | [string],
  'contactPhone' : string,
  'tiktokUrl' : string,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addBlogComment' : ActorMethod<
    [bigint, [] | [bigint], string, string, string],
    bigint
  >,
  'addBlogPost' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      Array<string>,
      string,
      string,
      string,
      boolean,
    ],
    bigint
  >,
  'addCommercialVehicle' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      bigint,
      string,
      string,
      string,
      Array<string>,
      string,
      string,
      string,
      string,
      Array<CommercialSpecItem>,
      boolean,
    ],
    string
  >,
  'addCreditRequirementTab' : ActorMethod<
    [string, Array<CreditRequirementItem>, bigint],
    CreditRequirementTab
  >,
  'addLead' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      bigint,
      bigint,
      bigint,
      bigint,
      string,
      bigint,
    ],
    Lead
  >,
  'addPassengerVehicle' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      Array<VehicleVariant>,
      Array<SpecTab>,
      boolean,
      string,
      Array<string>,
      Array<string>,
      string,
      string,
      string,
      string,
      string,
      [] | [string],
      [] | [string],
    ],
    bigint
  >,
  'addPromo' : ActorMethod<
    [
      string,
      string,
      string,
      [] | [string],
      [] | [string],
      [] | [string],
      bigint,
      bigint,
      string,
      Array<string>,
      boolean,
    ],
    bigint
  >,
  'addTestimonial' : ActorMethod<
    [
      string,
      string,
      string,
      bigint,
      string,
      string,
      string,
      string,
      string,
      boolean,
    ],
    bigint
  >,
  'approveBlogComment' : ActorMethod<[bigint], boolean>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'cleanupExpiredSessions' : ActorMethod<[], undefined>,
  'clearAllMediaAssets' : ActorMethod<[], undefined>,
  'deleteAdmin' : ActorMethod<[Principal], undefined>,
  'deleteBlogComment' : ActorMethod<[bigint], boolean>,
  'deleteBlogPost' : ActorMethod<[bigint], boolean>,
  'deleteCommercialVehicle' : ActorMethod<[string], boolean>,
  'deleteCreditRequirementTab' : ActorMethod<[string], boolean>,
  'deleteLead' : ActorMethod<[string], boolean>,
  'deleteMediaAsset' : ActorMethod<[bigint], boolean>,
  'deletePassengerVehicle' : ActorMethod<[bigint], boolean>,
  'deletePromo' : ActorMethod<[bigint], boolean>,
  'deleteTestimonial' : ActorMethod<[bigint], boolean>,
  'forceBecomeAdmin' : ActorMethod<[], string>,
  'forceSetMeAsSuperAdmin' : ActorMethod<[], string>,
  'getAdmins' : ActorMethod<[], Array<AdminRecord>>,
  'getAllBlogComments' : ActorMethod<[], Array<BlogComment>>,
  'getAllBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getAllCommercialVehicles' : ActorMethod<[], Array<CommercialVehicle>>,
  'getAllCreditRequirementTabs' : ActorMethod<[], Array<CreditRequirementTab>>,
  'getAllLeads' : ActorMethod<[], Array<Lead>>,
  'getAllMediaAssets' : ActorMethod<[], Array<MediaAsset>>,
  'getAllPassengerVehicles' : ActorMethod<[], Array<PassengerVehicle>>,
  'getAllPromos' : ActorMethod<[], Array<Promotion>>,
  'getAllTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getAllVisitorSessions' : ActorMethod<[], Array<VisitorSession>>,
  'getAllVisits' : ActorMethod<[], Array<Visit>>,
  'getApprovedCommentsByPostId' : ActorMethod<[bigint], Array<BlogComment>>,
  'getAssetsByDateRange' : ActorMethod<[bigint, bigint], Array<MediaAsset>>,
  'getAssetsByUploader' : ActorMethod<[Principal], Array<MediaAsset>>,
  'getBannerImages' : ActorMethod<[], Array<BannerImage>>,
  'getBlogPostById' : ActorMethod<[bigint], [] | [BlogPost]>,
  'getBlogPostBySlug' : ActorMethod<[string], [] | [BlogPost]>,
  'getBlogPostsByCategory' : ActorMethod<[string], Array<BlogPost>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getCommercialVehicleBySlug' : ActorMethod<
    [string, string],
    [] | [CommercialVehicle]
  >,
  'getCommercialVehicleCountByCategory' : ActorMethod<[string], bigint>,
  'getCommercialVehiclesByCategory' : ActorMethod<
    [string],
    Array<CommercialVehicle>
  >,
  'getCreditSettings' : ActorMethod<[], CreditSettings>,
  'getDailyVisitorTrend' : ActorMethod<[], Array<[bigint, bigint]>>,
  'getMediaAssetById' : ActorMethod<[bigint], [] | [MediaAsset]>,
  'getMyRole' : ActorMethod<[], [] | [UserRole]>,
  'getOnlineUsers' : ActorMethod<[], bigint>,
  'getPassengerVehicleById' : ActorMethod<[bigint], [] | [PassengerVehicle]>,
  'getPromoById' : ActorMethod<[bigint], [] | [Promotion]>,
  'getPromoBySlug' : ActorMethod<[string], [] | [Promotion]>,
  'getPublicMediaAssetById' : ActorMethod<[bigint], [] | [MediaAsset]>,
  'getPublicVisitorStats' : ActorMethod<[], VisitorStats>,
  'getPublishedBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getPublishedCommercialVehicles' : ActorMethod<[], Array<CommercialVehicle>>,
  'getPublishedPassengerVehicles' : ActorMethod<[], Array<PassengerVehicle>>,
  'getPublishedPromos' : ActorMethod<[], Array<Promotion>>,
  'getPublishedTestimonials' : ActorMethod<[], Array<Testimonial>>,
  'getStableVisitorStats' : ActorMethod<[], VisitorStats>,
  'getTestimonialById' : ActorMethod<[bigint], [] | [Testimonial]>,
  'getTopPageViews' : ActorMethod<[], Array<[string, bigint]>>,
  'getTotalPageViews' : ActorMethod<[], bigint>,
  'getTotalVisitors' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVisitorStats' : ActorMethod<[], VisitorStats>,
  'getWebsiteSettings' : ActorMethod<[], WebsiteSettings>,
  'initAdmin' : ActorMethod<[], string>,
  'initializeFirstAdmin' : ActorMethod<[], string>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likeBlogPost' : ActorMethod<[bigint], undefined>,
  'periodicCleanup' : ActorMethod<[], undefined>,
  'reorderCommercialVehicles' : ActorMethod<[Array<string>], undefined>,
  'reorderPassengerVehicles' : ActorMethod<[Array<bigint>], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'togglePassengerVehiclePublishStatus' : ActorMethod<[bigint], boolean>,
  'trackVisitor' : ActorMethod<
    [string, string, string, string, string, string, string],
    undefined
  >,
  'updateAdminRole' : ActorMethod<[Principal, UserRole], undefined>,
  'updateBlogPost' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      string,
      string,
      Array<string>,
      string,
      string,
      string,
      boolean,
    ],
    undefined
  >,
  'updateCommercialVehicle' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      bigint,
      string,
      string,
      string,
      Array<string>,
      string,
      string,
      string,
      string,
      Array<CommercialSpecItem>,
      boolean,
    ],
    boolean
  >,
  'updateCreditRequirementTab' : ActorMethod<
    [string, string, Array<CreditRequirementItem>, bigint],
    CreditRequirementTab
  >,
  'updateCreditSettings' : ActorMethod<
    [bigint, number, number, number, string],
    CreditSettings
  >,
  'updateMediaAsset' : ActorMethod<
    [bigint, string, string, string, bigint],
    undefined
  >,
  'updatePassengerVehicle' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      Array<VehicleVariant>,
      Array<SpecTab>,
      boolean,
      string,
      Array<string>,
      Array<string>,
      string,
      string,
      string,
      string,
      string,
      [] | [string],
      [] | [string],
    ],
    undefined
  >,
  'updatePromo' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      [] | [string],
      [] | [string],
      [] | [string],
      bigint,
      bigint,
      string,
      Array<string>,
      boolean,
    ],
    undefined
  >,
  'updateTestimonial' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      bigint,
      string,
      string,
      string,
      string,
      string,
      boolean,
    ],
    undefined
  >,
  'updateWebsiteSettings' : ActorMethod<[WebsiteSettings], undefined>,
  'uploadBannerImage' : ActorMethod<
    [string, BannerImageType, string, string, bigint],
    bigint
  >,
  'uploadMediaAsset' : ActorMethod<[string, string, string, bigint], bigint>,
  'whoAmI' : ActorMethod<[], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];